/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Principal.java
 *
 * Created on 16/09/2011, 14:19:48
 */
package jdbc.mvc.view;

import jdbc.mvc.controller.SystemMethods;

/**
 *
 * @author Guilherme
 */
public class Principal extends javax.swing.JFrame {

    /** Creates new form Principal */
    public Principal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        Cadastro = new javax.swing.JMenu();
        CadastraPessoa = new javax.swing.JMenuItem();
        Cadastraevento = new javax.swing.JMenuItem();
        CadastraUsuario = new javax.swing.JMenuItem();
        CadastraTipoEvento = new javax.swing.JMenuItem();
        CadastraMalaDireta = new javax.swing.JMenuItem();
        CadastraFilho = new javax.swing.JMenuItem();
        CadastraEmail = new javax.swing.JMenuItem();
        CadastraCategoriaPessoa = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Arquivo");

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbc/mvc/view/icons/Harddisk.png"))); // NOI18N
        jMenu3.setText("Backup");

        jMenuItem2.setText("Gerar arquivo de Backup");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Ler arquivo de Backup");
        jMenu3.add(jMenuItem3);

        jMenu1.add(jMenu3);
        jMenu1.add(jSeparator1);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbc/mvc/view/icons/Cancel.png"))); // NOI18N
        jMenuItem4.setText("Sair");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        Cadastro.setText("Cadastro");

        CadastraPessoa.setText("Cadastro de Pessoa");
        CadastraPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastraPessoaActionPerformed(evt);
            }
        });
        Cadastro.add(CadastraPessoa);

        Cadastraevento.setText("Cadastro de Evento");
        Cadastraevento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastraeventoActionPerformed(evt);
            }
        });
        Cadastro.add(Cadastraevento);

        CadastraUsuario.setText("Cadastro Usuário");
        CadastraUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastraUsuarioActionPerformed(evt);
            }
        });
        Cadastro.add(CadastraUsuario);

        CadastraTipoEvento.setText("Cadastro Tipo de Evento");
        CadastraTipoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastraTipoEventoActionPerformed(evt);
            }
        });
        Cadastro.add(CadastraTipoEvento);

        CadastraMalaDireta.setText("Cadastro Mala Direta");
        Cadastro.add(CadastraMalaDireta);

        CadastraFilho.setText("Cadastrar Filho");
        CadastraFilho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastraFilhoActionPerformed(evt);
            }
        });
        Cadastro.add(CadastraFilho);

        CadastraEmail.setText("Cadastrar Email");
        Cadastro.add(CadastraEmail);

        CadastraCategoriaPessoa.setText("Cadastro de Categoria de Pessoa");
        CadastraCategoriaPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastraCategoriaPessoaActionPerformed(evt);
            }
        });
        Cadastro.add(CadastraCategoriaPessoa);

        jMenuBar1.add(Cadastro);

        jMenu2.setText("Configurações");

        jMenuItem1.setText("Banco de Dados");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        TelaConfiguracoesBd telaConfiguracao = new TelaConfiguracoesBd(this, true);
        telaConfiguracao.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        TelaGerarBk tela = new TelaGerarBk(this, true);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void CadastraPessoaActionPerformed(java.awt.event.ActionEvent evt) {                                               

    CadastroPessoa x = new CadastroPessoa(this, true);
    x.setVisible(true);
    
    }
        private void CadastraeventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastraeventoActionPerformed

            // TODO add your handling code here:
        CadastroEvento x = new CadastroEvento(this, true);
        x.setVisible(true);

        }//GEN-LAST:event_CadastraeventoActionPerformed

    private void CadastraTipoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastraTipoEventoActionPerformed


        CadastroTipoEvento x = new CadastroTipoEvento(this, true);
        x.setVisible(true);

        }//GEN-LAST:event_CadastraTipoEventoActionPerformed

    private void CadastraFilhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastraFilhoActionPerformed

        CadastroFilho x = new CadastroFilho(this, true);
        x.setVisible(true);

        }//GEN-LAST:event_CadastraFilhoActionPerformed

    private void CadastraCategoriaPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastraCategoriaPessoaActionPerformed

        CadastroCategoriaPessoa x = new CadastroCategoriaPessoa(this, true);
        x.setVisible(true);

        }//GEN-LAST:event_CadastraCategoriaPessoaActionPerformed

    private void CadastraUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastraUsuarioActionPerformed
        // TODO add your handling code here:

        CadastroUsuario x = new CadastroUsuario(this, true);
        x.setVisible(true);

    }//GEN-LAST:event_CadastraUsuarioActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadastraCategoriaPessoa;
    private javax.swing.JMenuItem CadastraEmail;
    private javax.swing.JMenuItem CadastraFilho;
    private javax.swing.JMenuItem CadastraMalaDireta;
    private javax.swing.JMenuItem CadastraPessoa;
    private javax.swing.JMenuItem CadastraTipoEvento;
    private javax.swing.JMenuItem CadastraUsuario;
    private javax.swing.JMenuItem Cadastraevento;
    private javax.swing.JMenu Cadastro;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
