/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaConfiguracoesEmail.java
 *
 * Created on 25/09/2011, 20:42:42
 */
package jdbc.mvc.view;

import javax.swing.JOptionPane;
import jdbc.mvc.controller.ConfiguracoesSmtp_CRUD;
import jdbc.mvc.model.ConfiguracoesSmtp;

/**
 *
 * @author Guilherme
 */
public class TelaConfiguracoesEmail extends javax.swing.JDialog {
    
    ConfiguracoesSmtp_CRUD c = new ConfiguracoesSmtp_CRUD();
    ConfiguracoesSmtp config = new ConfiguracoesSmtp();

    /** Creates new form TelaConfiguracoesEmail */
    public TelaConfiguracoesEmail(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        ConfiguracoesSmtp_CRUD c = new ConfiguracoesSmtp_CRUD();
        ConfiguracoesSmtp config = new ConfiguracoesSmtp();
        
        config = c.leConfiguracaoSmtp();
        
        jTextField1.setText(config.getEndereco());
        jTextField2.setText(config.getUsuario());
        jTextField3.setText(String.valueOf(config.getPorta()));
        jPasswordField1.setText(config.getSenha());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configurações");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configurações de Conexão", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        jLabel1.setDisplayedMnemonic('n');
        jLabel1.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel1.setLabelFor(jTextField1);
        jLabel1.setText("Endereço do Servidor SMTP:");

        jTextField1.setText("smtp.seudominio");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel5.setDisplayedMnemonic('p');
        jLabel5.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel5.setLabelFor(jPasswordField1);
        jLabel5.setText("Senha:");

        jLabel2.setDisplayedMnemonic('o');
        jLabel2.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel2.setLabelFor(jTextField2);
        jLabel2.setText("Usuário:");

        jTextField2.setText("crm");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setDisplayedMnemonic('u');
        jLabel3.setFont(new java.awt.Font("Arial", 0, 11));
        jLabel3.setLabelFor(jTextField3);
        jLabel3.setText("Porta:");

        jTextField3.setText("25");

        jPasswordField1.setText("       ");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbc/mvc/view/icons/OK.png"))); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(3, 3, 3)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField3)
                                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-396)/2, (screenSize.height-242)/2, 396, 242);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

        // TODO add your handling code here:

        }//GEN-LAST:event_jTextField1ActionPerformed

        private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed

        // TODO add your handling code here:

        }//GEN-LAST:event_jTextField2ActionPerformed

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

            //verifica se o campo do endereço foi preenchido
            if(jTextField1.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Por favor preencha o campo do endereço do servidor SMTP!", "Configuração", JOptionPane.INFORMATION_MESSAGE);
                jTextField1.requestFocus(); // seta foco
                return; // sai da funcao
            }
            
            //verifica se o campo do endereço foi preenchido
            if(jTextField2.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Por favor preencha o campo do usuário do servidor SMTP!", "Configuração", JOptionPane.INFORMATION_MESSAGE);
                jTextField2.requestFocus(); // seta foco
                return; // sai da funcao
            }
            
            //verifica se o campo do endereço foi preenchido
            if(jPasswordField1.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Por favor preencha o campo da senha do servidor SMTP!", "Configuração", JOptionPane.INFORMATION_MESSAGE);
                jPasswordField1.requestFocus(); // seta foco
                return; // sai da funcao
            }
            
            //verifica se o campo do endereço foi preenchido
            if(jTextField3.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Por favor preencha o campo do usuário do servidor SMTP!", "Configuração", JOptionPane.INFORMATION_MESSAGE);
                jTextField3.requestFocus(); // seta foco
                return; // sai da funcao
            } else {
                //verifica se é numero
                
                int porta;
                
                try {
                    porta = Integer.parseInt(jTextField3.getText());
                } catch(NumberFormatException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(rootPane, "Porta SMTP inválida!", "Configuração", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
                
                config.setEndereco(jTextField1.getText());
                config.setUsuario(jTextField2.getText());
                config.setSenha(jPasswordField1.getText());
                config.setPorta(porta);
                
                String[] botoes = {"Sim","Não"};  //botoes a substituir o JOptionPane.YES_NO_OPTION
        
              if (JOptionPane.showOptionDialog(null, 
                        "Deseja salvar estas configurações?\n\n"
                        + "Endereço do Servidor SMTP: " + config.getEndereco() + "\n"
                        + "Usuário: " + config.getUsuario() 
                        + "\n"+ "Porta: " + config.getPorta() + "\n",
                        "Configurações",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE,null, botoes, botoes[1]) == 0) {
                                    c.gravaConfiguracaoSmtp(config);
               }
            }

        }//GEN-LAST:event_jButton1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoesEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoesEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoesEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoesEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                TelaConfiguracoesEmail dialog = new TelaConfiguracoesEmail(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
